name: Deploy to Zone
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://YOURDOMAIN.EU
    steps:
      - name: Checkout to main
        uses: actions/checkout@main

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Debug SSH variables
        run: |
          echo "User: ${{ secrets.SSH_USER }}"
          echo "Host: ${{ secrets.HOST_SERVER_IP }}"

      - name: Debug SSH connection
        run: |
          # Add verbose output for debugging
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.HOST_SERVER_IP }} "echo Connection test"

      - name: Copy files to server
        if: success()
        run: |
          rsync -avz --delete --exclude=".git*" --exclude="node_modules" ./ ${{ secrets.SSH_USER }}@${{ secrets.HOST_SERVER_IP }}:${{ secrets.DEPLOY_PATH }}
